const questions = {
    mathematics: [
        // ── BASIC OPERATIONS (18 questions) ──
        { question: "What is 47 + 38?", options: ["85", "75", "95"], answer: 0 },
        { question: "What is 150 - 67?", options: ["93", "83", "73"], answer: 1 },
        { question: "What is 14 × 6?", options: ["74", "94", "84"], answer: 2 },
        { question: "What is 144 ÷ 12?", options: ["12", "14", "16"], answer: 0 },
        { question: "What is 235 + 465?", options: ["690", "700", "710"], answer: 1 },
        { question: "What is 500 - 238?", options: ["272", "252", "262"], answer: 2 },
        { question: "What is 19 × 5?", options: ["95", "85", "105"], answer: 0 },
        { question: "What is 216 ÷ 6?", options: ["32", "36", "38"], answer: 1 },
        { question: "What is 89 + 54?", options: ["133", "153", "143"], answer: 2 },
        { question: "What is 1000 - 455?", options: ["545", "555", "535"], answer: 0 },
        { question: "What is 25 × 12?", options: ["280", "300", "320"], answer: 1 },
        { question: "What is 360 ÷ 9?", options: ["30", "50", "40"], answer: 2 },
        { question: "What is 17 × 4?", options: ["68", "72", "64"], answer: 0 },
        { question: "What is 750 ÷ 25?", options: ["25", "30", "35"], answer: 1 },
        { question: "What is 389 + 121?", options: ["500", "520", "510"], answer: 2 },
        { question: "What is 600 - 187?", options: ["413", "423", "403"], answer: 0 },
        { question: "What is 16 × 7?", options: ["102", "112", "122"], answer: 1 },
        { question: "What is 480 ÷ 16?", options: ["20", "40", "30"], answer: 2 },

        // ── PEMDAS / ORDER OF OPERATIONS (16 questions) ──
        { question: "What is 8 + 3 × 4?", options: ["20", "44", "24"], answer: 0 },
        { question: "What is (12 - 4) × 5?", options: ["35", "40", "45"], answer: 1 },
        { question: "What is 20 ÷ 4 + 6?", options: ["9", "10", "11"], answer: 2 },
        { question: "What is 15 - 2 × 3 + 1?", options: ["10", "12", "40"], answer: 0 },
        { question: "What is (6 + 4) ÷ (7 - 2)?", options: ["1", "2", "3"], answer: 1 },
        { question: "What is 4² + 3 × 2?", options: ["38", "14", "22"], answer: 2 },
        { question: "What is 5 × (8 - 3) + 2?", options: ["27", "25", "29"], answer: 0 },
        { question: "What is 30 - 3 × 4 + 2?", options: ["18", "20", "110"], answer: 1 },
        { question: "What is (5 + 3)² ÷ 8?", options: ["4", "16", "8"], answer: 2 },
        { question: "What is 18 ÷ 3 × 2?", options: ["12", "3", "6"], answer: 0 },
        { question: "What is 10 + 2 × (6 - 1)?", options: ["30", "20", "25"], answer: 1 },
        { question: "What is 24 ÷ (2 + 4) × 3?", options: ["4", "2", "12"], answer: 2 },
        { question: "What is (15 - 5) × (2 + 3)?", options: ["50", "45", "55"], answer: 0 },
        { question: "What is 9 + 6 ÷ 3 - 2?", options: ["3", "9", "5"], answer: 1 },
        { question: "What is 2³ + 4 × 5?", options: ["40", "26", "28"], answer: 2 },
        { question: "What is 50 - (4 × 5 + 10)?", options: ["20", "30", "10"], answer: 0 },

        // ── SHAPES & GEOMETRY (16 questions) ──
        { question: "How many sides does a hexagon have?", options: ["6", "7", "8"], answer: 0 },
        { question: "What is a triangle with all equal sides called?", options: ["Isosceles", "Equilateral", "Scalene"], answer: 1 },
        { question: "How many faces does a standard cube have?", options: ["8", "12", "6"], answer: 2 },
        { question: "What do you call an angle greater than 90° and less than 180°?", options: ["Obtuse", "Acute", "Reflex"], answer: 0 },
        { question: "How many sides does an octagon have?", options: ["6", "8", "10"], answer: 1 },
        { question: "What is the sum of interior angles in a triangle?", options: ["90°", "360°", "180°"], answer: 2 },
        { question: "What 3D shape has 1 circular base and 1 vertex?", options: ["Cone", "Cylinder", "Sphere"], answer: 0 },
        { question: "How many degrees are in a full circle?", options: ["180°", "360°", "720°"], answer: 1 },
        { question: "A quadrilateral with only one pair of parallel sides is a?", options: ["Rhombus", "Parallelogram", "Trapezoid"], answer: 2 },
        { question: "How many sides does a nonagon have?", options: ["9", "10", "11"], answer: 0 },
        { question: "What is the perimeter formula for a square with side 's'?", options: ["s²", "4s", "2s"], answer: 1 },
        { question: "What 3D shape has 2 parallel circular bases?", options: ["Cone", "Prism", "Cylinder"], answer: 2 },
        { question: "What do you call an angle exactly equal to 90°?", options: ["Right angle", "Straight angle", "Acute angle"], answer: 0 },
        { question: "How many vertices does a rectangular cuboid have?", options: ["6", "8", "12"], answer: 1 },
        { question: "What is a 5-sided polygon called?", options: ["Hexagon", "Heptagon", "Pentagon"], answer: 2 },
        { question: "What is the sum of angles in a quadrilateral?", options: ["360°", "180°", "540°"], answer: 0 }
    ],

    science: [
        // ── ANIMALS (13 questions) ──
        { question: "Which mammal is capable of true sustained flight?", options: ["Bat", "Flying Squirrel", "Sugar Glider"], answer: 0 },
        { question: "What is the largest mammal currently living on Earth?", options: ["African Elephant", "Blue Whale", "Colossal Squid"], answer: 1 },
        { question: "What do you call animals that feed exclusively on plants?", options: ["Carnivores", "Omnivores", "Herbivores"], answer: 2 },
        { question: "Which animal group has cold blood and lays eggs with leathery shells?", options: ["Reptiles", "Amphibians", "Mammals"], answer: 0 },
        { question: "How many legs does a spider have?", options: ["6", "8", "10"], answer: 1 },
        { question: "What is the fastest land animal in the world?", options: ["Lion", "Falcon", "Cheetah"], answer: 2 },
        { question: "Which bird is famous for being flightless and swimming in icy seas?", options: ["Penguin", "Ostrich", "Kiwi"], answer: 0 },
        { question: "What organ do fish use to absorb dissolved oxygen from water?", options: ["Lungs", "Gills", "Spiracles"], answer: 1 },
        { question: "What is an animal active primarily during the night called?", options: ["Diurnal", "Crepuscular", "Nocturnal"], answer: 2 },
        { question: "Which animal is the largest living land carnivore?", options: ["Polar Bear", "Grizzly Bear", "Bengal Tiger"], answer: 0 },
        { question: "What is a collective group of lions called?", options: ["Pack", "Pride", "Flock"], answer: 1 },
        { question: "Which marine creature possesses three hearts and blue blood?", options: ["Jellyfish", "Starfish", "Octopus"], answer: 2 },
        { question: "What organ can amphibians use to breathe through besides lungs?", options: ["Skin", "Scales", "Antennae"], answer: 0 },

        // ── HUMAN BODY (13 questions) ──
        { question: "What is the largest organ of the human body?", options: ["Liver", "Skin", "Lungs"], answer: 1 },
        { question: "How many bones are in the typical adult human skeleton?", options: ["186", "256", "206"], answer: 2 },
        { question: "Which organ continuously pumps blood throughout the circulatory system?", options: ["Heart", "Brain", "Stomach"], answer: 0 },
        { question: "Which blood cells are responsible for carrying oxygen to body tissues?", options: ["White Blood Cells", "Red Blood Cells", "Platelets"], answer: 1 },
        { question: "Which bony structure protects the human brain?", options: ["Ribcage", "Pelvis", "Skull (Cranium)"], answer: 2 },
        { question: "What is the primary function of the kidneys?", options: ["Filtering waste from blood", "Pumping oxygen", "Digesting fats"], answer: 0 },
        { question: "Which part of the eye regulates the amount of light entering?", options: ["Retina", "Iris", "Cornea"], answer: 1 },
        { question: "What fibrous tissue connects skeletal muscles to bones?", options: ["Ligaments", "Cartilage", "Tendons"], answer: 2 },
        { question: "Which organ produces insulin to maintain glucose balance?", options: ["Pancreas", "Gallbladder", "Spleen"], answer: 0 },
        { question: "How many chambers make up the human heart?", options: ["2", "4", "6"], answer: 1 },
        { question: "What is the longest and strongest bone in the human body?", options: ["Tibia", "Humerus", "Femur"], answer: 2 },
        { question: "Where does the majority of nutrient absorption take place?", options: ["Small Intestine", "Stomach", "Large Intestine"], answer: 0 },
        { question: "What acts as the command center of the central nervous system?", options: ["Spinal Cord", "Brain", "Heart"], answer: 1 },

        // ── SOLAR SYSTEM (12 questions) ──
        { question: "Which planet is situated closest to the Sun?", options: ["Venus", "Mars", "Mercury"], answer: 2 },
        { question: "Which planet is nicknamed the 'Red Planet' due to iron oxide?", options: ["Mars", "Jupiter", "Saturn"], answer: 0 },
        { question: "What is the largest planet in our Solar System?", options: ["Saturn", "Jupiter", "Neptune"], answer: 1 },
        { question: "Which planet is famous for its bright, extensive ring system?", options: ["Uranus", "Neptune", "Saturn"], answer: 2 },
        { question: "What luminous star sits at the center of our Solar System?", options: ["The Sun", "Proxima Centauri", "Sirius"], answer: 0 },
        { question: "Which planet is considered Earth's sister planet due to similar size?", options: ["Mars", "Venus", "Mercury"], answer: 1 },
        { question: "What natural satellite orbits the Earth?", options: ["Phobos", "Titan", "The Moon"], answer: 2 },
        { question: "What is the hottest planet in the Solar System due to runaway greenhouse effect?", options: ["Venus", "Mercury", "Mars"], answer: 0 },
        { question: "Which planet rotates on its side with an axial tilt of nearly 98°?", options: ["Neptune", "Uranus", "Saturn"], answer: 1 },
        { question: "What region of rocky bodies lies between the orbits of Mars and Jupiter?", options: ["Kuiper Belt", "Oort Cloud", "Asteroid Belt"], answer: 2 },
        { question: "Which is the most distant official planet from the Sun?", options: ["Neptune", "Uranus", "Pluto"], answer: 0 },
        { question: "What event occurs when the Moon passes directly between the Sun and Earth?", options: ["Lunar Eclipse", "Solar Eclipse", "Aurora"], answer: 1 },

        // ── STATES OF MATTER (12 questions) ──
        { question: "Which state of matter maintains both a fixed shape and fixed volume?", options: ["Gas", "Liquid", "Solid"], answer: 2 },
        { question: "What is the phase change from liquid to gas called?", options: ["Evaporation", "Condensation", "Freezing"], answer: 0 },
        { question: "What state of matter flows to take the shape of its container while keeping a fixed volume?", options: ["Solid", "Liquid", "Plasma"], answer: 1 },
        { question: "What is the direct transition from solid to gas without becoming liquid?", options: ["Deposition", "Melting", "Sublimation"], answer: 2 },
        { question: "What high-energy ionized state of matter is found in stars and neon signs?", options: ["Plasma", "Bose-Einstein", "Gas"], answer: 0 },
        { question: "What is the phase change from gas to liquid called?", options: ["Sublimation", "Condensation", "Vaporization"], answer: 1 },
        { question: "At what temperature Celsius does water freeze at normal pressure?", options: ["32°C", "100°C", "0°C"], answer: 2 },
        { question: "What is the boiling point of pure water at 1 atmosphere of pressure?", options: ["100°C", "90°C", "120°C"], answer: 0 },
        { question: "What happens to the kinetic energy of particles as temperature increases?", options: ["Decreases", "Increases", "Remains zero"], answer: 1 },
        { question: "What is the phase change called when gas transforms directly into solid (like frost)?", options: ["Freezing", "Sublimation", "Deposition"], answer: 2 },
        { question: "Which state of matter expands freely to fill any container volume?", options: ["Gas", "Liquid", "Solid"], answer: 0 },
        { question: "What cohesive force causes water droplets to form beads on surfaces?", options: ["Viscosity", "Surface Tension", "Density"], answer: 1 }
    ],

    history: [
        // ── PHILIPPINE HEROES (13 questions) ──
        { question: "Who is celebrated as the National Hero of the Philippines?", options: ["Andres Bonifacio", "Emilio Aguinaldo", "Dr. Jose Rizal"], answer: 2 },
        { question: "Who was the 'Supremo' that founded the Katipunan (KKK)?", options: ["Andres Bonifacio", "Apolinario Mabini", "Juan Luna"], answer: 0 },
        { question: "Who was known as the 'Brain of the Revolution' and the 'Sublime Paralytic'?", options: ["Emilio Jacinto", "Apolinario Mabini", "Antonio Luna"], answer: 1 },
        { question: "Who is known as 'Tandang Sora', the Mother of the Katipunan?", options: ["Gabriela Silang", "Trinidad Tecson", "Melchora Aquino"], answer: 2 },
        { question: "Who led revolutionary troops in Ilocos after the assassination of her husband Diego?", options: ["Gabriela Silang", "Gregoria de Jesus", "Teresa Magbanua"], answer: 0 },
        { question: "Who was the fiery pharmacist-general who commanded Philippine revolutionary forces?", options: ["Gregorio del Pilar", "Antonio Luna", "Artemio Ricarte"], answer: 1 },
        { question: "Who was the youngest general in the revolutionary army who fell at Tirad Pass?", options: ["Emilio Aguinaldo", "Macario Sakay", "Gregorio del Pilar"], answer: 2 },
        { question: "Who authored the moral and ethical code 'Kartilya ng Katipunan'?", options: ["Emilio Jacinto", "Jose Rizal", "Marcelo H. del Pilar"], answer: 0 },
        { question: "Who painted the celebrated historical painting 'Spoliarium' in Madrid?", options: ["Felix Hidalgo", "Juan Luna", "Fernando Amorsolo"], answer: 1 },
        { question: "Who led the longest insurrection against Spanish colonial rule in Bohol (85 years)?", options: ["Diego Silang", "Tamblot", "Francisco Dagohoy"], answer: 2 },
        { question: "Who was the Mactan chieftain who defeated Magellan in the Battle of Mactan (1521)?", options: ["Lapu-Lapu", "Rajah Humabon", "Rajah Sulayman"], answer: 0 },
        { question: "Who was known as the 'Lakambini ng Katipunan' and custodian of revolutionary documents?", options: ["Melchora Aquino", "Gregoria de Jesus", "Marina Dizon"], answer: 1 },
        { question: "Who was the great orator and first editor of the reformist paper 'La Solidaridad'?", options: ["Jose Rizal", "Marcelo H. del Pilar", "Graciano Lopez Jaena"], answer: 2 },

        // ── PRESIDENTS OF THE PHILIPPINES (13 questions) ──
        { question: "Who was the first President of the Philippine Republic (First Republic / Malolos)?", options: ["Emilio Aguinaldo", "Manuel L. Quezon", "Jose P. Laurel"], answer: 0 },
        { question: "Who served as Commonwealth President and is hailed as 'Father of the National Language'?", options: ["Sergio Osmeña", "Manuel L. Quezon", "Manuel Roxas"], answer: 1 },
        { question: "Who became the first female President of the Philippines following the 1986 People Power?", options: ["Gloria Macapagal Arroyo", "Imelda Marcos", "Corazon Aquino"], answer: 2 },
        { question: "Which beloved President was famously known as the 'Champion of the Masses'?", options: ["Ramon Magsaysay", "Elpidio Quirino", "Carlos P. Garcia"], answer: 0 },
        { question: "Which President championed the 'Filipino First' economic policy?", options: ["Diosdado Macapagal", "Carlos P. Garcia", "Ferdinand Marcos Sr."], answer: 1 },
        { question: "Who served as President during the Japanese-sponsored Second Philippine Republic?", options: ["Manuel Quezon", "Sergio Osmeña", "Jose P. Laurel"], answer: 2 },
        { question: "Who was inaugurated as the first President of the Third Republic on July 4, 1946?", options: ["Manuel Roxas", "Elpidio Quirino", "Ramon Magsaysay"], answer: 0 },
        { question: "Which President moved the official Philippine Independence Day celebration to June 12?", options: ["Carlos P. Garcia", "Diosdado Macapagal", "Ferdinand Marcos Sr."], answer: 1 },
        { question: "Which President launched the 'Philippines 2000' economic vision?", options: ["Joseph Estrada", "Corazon Aquino", "Fidel V. Ramos"], answer: 2 },
        { question: "Who assumed the presidency following the EDSA People Power II revolution in 2001?", options: ["Gloria Macapagal Arroyo", "Benigno Aquino III", "Fidel V. Ramos"], answer: 0 },
        { question: "Who was inaugurated in 2016 as the first Philippine President from Mindanao?", options: ["Manny Pacquiao", "Rodrigo Duterte", "Aquilino Pimentel"], answer: 1 },
        { question: "Who served as the 2nd Commonwealth President after Quezon passed away in 1944?", options: ["Jose P. Laurel", "Manuel Roxas", "Sergio Osmeña"], answer: 2 },
        { question: "Who was the 15th President of the Philippines, affectionately called 'PNoy'?", options: ["Benigno 'Noynoy' Aquino III", "Fidel Ramos", "Joseph Estrada"], answer: 0 },

        // ── FESTIVALS (12 questions) ──
        { question: "Which world-famous Cebu festival honors the Santo Niño with drumbeats and forward-backward dancing?", options: ["Panagbenga", "Sinulog Festival", "Dinagyang"], answer: 1 },
        { question: "Which colorful flower festival is celebrated annually every February in Baguio City?", options: ["Pahiyas", "MassKara", "Panagbenga Festival"], answer: 2 },
        { question: "Which Quezon festival decorates houses with vibrant kiping rice wafers in thanksgiving to San Isidro?", options: ["Pahiyas Festival", "Ati-Atihan", "Kadayawan"], answer: 0 },
        { question: "Which Bacolod festival was created to bring back smiles with vibrant smiling masks?", options: ["Sinulog", "MassKara Festival", "Moriones"], answer: 1 },
        { question: "Which Holy Week festival in Marinduque features men and women dressed as Roman centurions?", options: ["Dinagyang", "Higantes", "Moriones Festival"], answer: 2 },
        { question: "Which grand Davao City festival celebrates the 11 indigenous tribes and rich harvest?", options: ["Kadayawan Festival", "Pahiyas", "T'nalak"], answer: 0 },
        { question: "Which Aklan festival is celebrated with soot-painted bodies and shouts of 'Hala Bira!'?", options: ["Sinulog", "Ati-Atihan Festival", "Dinagyang"], answer: 1 },
        { question: "Which Iloilo festival is famous for its drum rhythms and dramatic warrior tribe choreography?", options: ["MassKara", "Pintados", "Dinagyang Festival"], answer: 2 },
        { question: "Which Angono, Rizal festival parades giant papier-mâché figures representing local folklore?", options: ["Higantes Festival", "Moriones", "Kadayawan"], answer: 0 },
        { question: "Which Leyte festival celebrates the tattooed ancient warrior ancestors of the Visayas?", options: ["Ati-Atihan", "Pintados-Kasadyaan Festival", "Sinulog"], answer: 1 },
        { question: "Which Pampanga festival showcases enormous, kaleidoscopic illuminated lanterns every Christmas?", options: ["Pahiyas", "MassKara", "Giant Lantern Festival (Ligligan Parul)"], answer: 2 },
        { question: "Which San Juan City festival features friendly community water-dousing to honor St. John the Baptist?", options: ["Wattah Wattah Festival", "Batingaw Festival", "Sinulog"], answer: 0 },

        // ── ANCIENT CIVILIZATIONS (12 questions) ──
        { question: "Which historical cradle of civilization developed between the Tigris and Euphrates rivers?", options: ["Egypt", "Mesopotamia", "Indus Valley"], answer: 1 },
        { question: "Which civilization built the Great Pyramid of Giza and preserved pharaohs in tombs?", options: ["Romans", "Greeks", "Ancient Egypt"], answer: 2 },
        { question: "Which ancient Greek city-state developed the foundations of democracy and philosophical academies?", options: ["Athens", "Sparta", "Corinth"], answer: 0 },
        { question: "What was the ancient Egyptian writing system that utilized pictorial glyphs?", options: ["Cuneiform", "Hieroglyphics", "Latin"], answer: 1 },
        { question: "Which Mesopotamian civilization created the wedge-shaped script known as cuneiform?", options: ["Phoenicians", "Hittites", "Sumerians"], answer: 2 },
        { question: "Which wonder of the ancient world was reportedly built in Babylon with terraced gardens?", options: ["Hanging Gardens of Babylon", "Lighthouse of Alexandria", "Colossus of Rhodes"], answer: 0 },
        { question: "Which ancient empire constructed the Colosseum, extensive paved roads, and stone aqueducts?", options: ["Macedonians", "Roman Empire", "Persians"], answer: 1 },
        { question: "Which Mesoamerican civilization built stepped pyramids like Kukulkan at Chichen Itza?", options: ["Inca", "Olmec", "Maya Civilization"], answer: 2 },
        { question: "Which South American empire built the stone citadel of Machu Picchu high in the Andes?", options: ["Inca Empire", "Aztec", "Maya"], answer: 0 },
        { question: "Which civilization established its early dynasties along the Yellow and Yangtze rivers?", options: ["Indus Valley", "Ancient China", "Persia"], answer: 1 },
        { question: "What ancient network of trade routes connected China, Central Asia, and Europe for centuries?", options: ["Amber Route", "Incense Path", "The Silk Road"], answer: 2 },
        { question: "Which African river provided annual floods essential for ancient Egyptian agriculture?", options: ["The Nile River", "Tigris River", "Congo River"], answer: 0 }
    ],

    technology: [
        // ── COMPUTER PARTS & HARDWARE (50 questions) ──
        { question: "What does CPU stand for?", options: ["Central Processing Unit", "Computer Power Utility", "Central Performance Unit"], answer: 0 },
        { question: "Which computer component is commonly nicknamed the 'brain' of the computer?", options: ["Graphics Card", "Central Processing Unit (CPU)", "Hard Drive"], answer: 1 },
        { question: "What does RAM stand for in computer hardware?", options: ["Rapid Action Module", "Read Always Memory", "Random Access Memory"], answer: 2 },
        { question: "What type of memory is system RAM?", options: ["Volatile (cleared when powered off)", "Non-volatile (permanent)", "Magnetic tape storage"], answer: 0 },
        { question: "What does GPU stand for?", options: ["General Processing Unit", "Graphics Processing Unit", "Gaming Performance Utility"], answer: 1 },
        { question: "What is the primary role of a GPU in a computer system?", options: ["Storing system files", "Cooling the processor", "Rendering images, 3D graphics, and video"], answer: 2 },
        { question: "What is the main printed circuit board that connects all computer parts together?", options: ["Motherboard", "Power Supply Unit", "Sound Card"], answer: 0 },
        { question: "What does SSD stand for in storage devices?", options: ["Super Speed Disk", "Solid State Drive", "System Storage Device"], answer: 1 },
        { question: "What does HDD stand for in computer storage?", options: ["High Data Drive", "Hybrid Dynamic Disk", "Hard Disk Drive"], answer: 2 },
        { question: "Why are SSDs significantly faster and more durable than HDDs?", options: ["They use flash memory without moving parts", "They use magnetic spinning platters", "They require liquid cooling"], answer: 0 },
        { question: "What does PSU stand for in computer systems?", options: ["Primary System Unit", "Power Supply Unit", "Processor Speed Utility"], answer: 1 },
        { question: "What is the primary function of a Power Supply Unit (PSU)?", options: ["Cooling the motherboard", "Storing BIOS firmware", "Converting AC wall power to low-voltage DC power"], answer: 2 },
        { question: "What compound is applied between the CPU and cooler to maximize heat transfer?", options: ["Thermal Paste", "Silicone Adhesive", "Conductive Gel"], answer: 0 },
        { question: "What passive cooling component uses aluminum or copper fins to disperse heat?", options: ["Expansion Card", "Heat Sink", "Sound Card"], answer: 1 },
        { question: "What does ROM stand for in computing?", options: ["Random Operational Module", "Rapid Output Mechanism", "Read-Only Memory"], answer: 2 },
        { question: "What low-level firmware stored in ROM initializes hardware when turning on a PC?", options: ["BIOS / UEFI", "Operating System", "Device Drivers"], answer: 0 },
        { question: "What is the primary input device used to type alphanumeric text into a PC?", options: ["Monitor", "Keyboard", "Microphone"], answer: 1 },
        { question: "What hand-held input device detects 2D motion relative to a surface to move a cursor?", options: ["Webcam", "Barometer", "Mouse"], answer: 2 },
        { question: "What output device visually renders the computer user interface on a screen?", options: ["Monitor / Display", "Scanner", "Modem"], answer: 0 },
        { question: "What component allows a computer to connect to a local area network via Ethernet?", options: ["GPU", "Network Interface Card (NIC)", "PSU"], answer: 1 },
        { question: "What does USB stand for?", options: ["Unified System Bus", "User Storage Backup", "Universal Serial Bus"], answer: 2 },
        { question: "Which digital port carries both high-definition video and multichannel audio?", options: ["HDMI", "VGA", "PS/2"], answer: 0 },
        { question: "What legacy blue 15-pin analog video connection was widely used on older monitors?", options: ["DisplayPort", "VGA (Video Graphics Array)", "DVI-D"], answer: 1 },
        { question: "What high-speed expansion slot on the motherboard is standard for dedicated GPUs?", options: ["PCI", "ISA", "PCIe x16"], answer: 2 },
        { question: "What coin-cell battery on the motherboard powers the real-time clock and BIOS memory?", options: ["CMOS Battery (CR2032)", "Lithium AA", "Alkaline 9V"], answer: 0 },
        { question: "What component handles audio processing and output for speakers or headphones?", options: ["Network Card", "Sound Card / Audio Chipset", "Capture Card"], answer: 1 },
        { question: "What drive reads data using laser beams on CDs, DVDs, or Blu-ray discs?", options: ["Card Reader", "Floppy Drive", "Optical Disc Drive"], answer: 2 },
        { question: "What cooling method circulates liquid through water blocks and radiators to cool components?", options: ["Liquid Cooling (AIO / Custom Loop)", "Air Cooling", "Passive Heatsink"], answer: 0 },
        { question: "What digital video camera connects to a PC to capture live video for video calls?", options: ["Projector", "Webcam", "Digitizer"], answer: 1 },
        { question: "What audio input device converts sound waves into electronic signals?", options: ["Speaker", "Earphone", "Microphone"], answer: 2 },
        { question: "What does the form factor 'ATX' define in computer hardware?", options: ["Motherboard and power supply physical dimensions", "CPU clock frequency", "RAM capacity limits"], answer: 0 },
        { question: "What ultra-fast SSD form factor plugs directly into the motherboard M.2 slot via PCIe?", options: ["SATA HDD", "NVMe M.2 SSD", "Floppy Diskette"], answer: 1 },
        { question: "What is the term for configuring hardware to run at speeds higher than manufacturer specs?", options: ["Underclocking", "Throttling", "Overclocking"], answer: 2 },
        { question: "What metric is standard for measuring modern processor clock speed?", options: ["Gigahertz (GHz)", "Megabytes (MB)", "Gigabits per second (Gbps)"], answer: 0 },
        { question: "What term describes the number of distinct pixels displayed on a screen (e.g. 1920×1080)?", options: ["Hertz", "Resolution", "Lumens"], answer: 1 },
        { question: "What monitor specification refers to how many times per second the display image updates?", options: ["Response Time (ms)", "Contrast Ratio", "Refresh Rate (Hz)"], answer: 2 },
        { question: "What internal ribbon cable connects 2.5-inch SSDs or HDDs to the motherboard?", options: ["SATA Cable", "Ethernet Cable", "DisplayPort Cable"], answer: 0 },
        { question: "What optical device captures physical paper documents and converts them to digital images?", options: ["Laser Printer", "Scanner", "Plotter"], answer: 1 },
        { question: "What output device prints physical hard-copy ink or toner onto paper?", options: ["Monitor", "Projector", "Printer"], answer: 2 },
        { question: "What device provides emergency battery backup power during electrical outages?", options: ["UPS (Uninterruptible Power Supply)", "Surge Protector Bar", "Capacitor Bank"], answer: 0 },
        { question: "What is the outer enclosure that houses and protects all computer internal components?", options: ["Server Rack", "Computer Case (Chassis)", "Faraday Cage"], answer: 1 },
        { question: "What extremely high-speed memory is built directly onto the CPU silicon die?", options: ["Virtual Memory", "ROM", "CPU Cache (L1, L2, L3)"], answer: 2 },
        { question: "Which DDR SDRAM memory standards are widely used in current modern desktop computers?", options: ["DDR4 and DDR5", "DDR1 and SDR", "EDO DRAM"], answer: 0 },
        { question: "What voltage regulation components on the motherboard manage power delivered to the CPU?", options: ["RGB Headers", "VRMs (Voltage Regulator Modules)", "CMOS Jumpers"], answer: 1 },
        { question: "What modern reversible connector is becoming universal for charging, video, and data transfer?", options: ["USB Type-A", "Micro-USB", "USB Type-C"], answer: 2 },
        { question: "What is each independent hardware computation unit inside a multi-core processor called?", options: ["CPU Core", "Thread", "Bus"], answer: 0 },
        { question: "What input device allows digital artists to draw directly on a touch-sensitive surface using a stylus?", options: ["Trackball", "Graphics Drawing Tablet", "Barcode Scanner"], answer: 1 },
        { question: "What short-range wireless standard connects wireless keyboards, mice, and headphones to a PC?", options: ["NFC", "Infrared", "Bluetooth"], answer: 2 },
        { question: "What is the primary role of intake and exhaust fans installed in a computer chassis?", options: ["Maintaining active airflow and exhausting heat", "Powering internal LEDs", "Eliminating dust automatically"], answer: 0 },
        { question: "What standard 8-pin modular connector is used on Ethernet network cables?", options: ["USB-B", "RJ-45 Connector", "3.5mm TRS Jack"], answer: 1 }
    ]
};
