const questions = {
    mathematics: [
        { question: "What is 5 + 7?", options: ["10", "12", "14"], answer: 1 },
        { question: "What is 8 × 9?", options: ["72", "64", "81"], answer: 0 },
        { question: "Square root of 144?", options: ["10", "12", "14"], answer: 1 },
        { question: "What is 15% of 100?", options: ["15", "10", "20"], answer: 0 },
        { question: "What is 3³ (3 cubed)?", options: ["9", "27", "81"], answer: 1 },
        { question: "What is 100 ÷ 4?", options: ["25", "20", "50"], answer: 0 },
        { question: "Value of Pi (approx)?", options: ["3.14", "2.71", "1.41"], answer: 0 },
        { question: "Sum of angles in a triangle?", options: ["180°", "360°", "90°"], answer: 0 },
        { question: "What is 7 × 6?", options: ["42", "36", "48"], answer: 0 },
        { question: "Next prime after 7?", options: ["11", "9", "13"], answer: 0 },
        { question: "What is 2⁵?", options: ["32", "64", "16"], answer: 0 },
        { question: "Perimeter of square with side 6?", options: ["24", "36", "12"], answer: 0 },
        { question: "What is 9 × 9?", options: ["72", "81", "99"], answer: 1 },
        { question: "Area of rectangle 5 × 8?", options: ["40", "26", "30"], answer: 0 },
        { question: "What is 144 ÷ 12?", options: ["10", "12", "14"], answer: 1 },
        { question: "What is 50% of 80?", options: ["30", "40", "50"], answer: 1 },
        { question: "Square root of 225?", options: ["12", "15", "18"], answer: 1 },
        { question: "What is 11 × 11?", options: ["111", "121", "131"], answer: 1 },
        { question: "Circumference formula for a circle?", options: ["πr²", "2πr", "4πr"], answer: 1 },
        { question: "What is 1000 ÷ 25?", options: ["40", "45", "50"], answer: 0 },
        { question: "What is 4! (4 factorial)?", options: ["16", "24", "12"], answer: 1 },
        { question: "What is the GCF of 12 and 18?", options: ["6", "3", "9"], answer: 0 },
        { question: "What is 0.5 × 0.5?", options: ["0.25", "0.5", "1.0"], answer: 0 },
        { question: "Angles in a right angle?", options: ["45°", "90°", "180°"], answer: 1 },
        { question: "What is 2⁸?", options: ["128", "256", "512"], answer: 1 },
        { question: "Hypotenuse of a 3-4-? triangle?", options: ["6", "5", "7"], answer: 1 },
        { question: "Least common multiple of 4 and 6?", options: ["8", "12", "24"], answer: 1 },
        { question: "What is 17 × 3?", options: ["48", "51", "54"], answer: 1 },
        { question: "Area of a triangle (base 10, height 6)?", options: ["30", "60", "16"], answer: 0 },
        { question: "What is √81?", options: ["7", "9", "11"], answer: 1 }
    ],
    science: [
        { question: "What planet is the Red Planet?", options: ["Earth", "Mars", "Venus"], answer: 1 },
        { question: "Chemical symbol for water?", options: ["H2O", "O2", "CO2"], answer: 0 },
        { question: "Force that keeps us on the ground?", options: ["Magnetism", "Gravity", "Friction"], answer: 1 },
        { question: "Gas plants absorb in photosynthesis?", options: ["Oxygen", "Carbon Dioxide", "Nitrogen"], answer: 1 },
        { question: "Hardest natural substance on Earth?", options: ["Gold", "Diamond", "Iron"], answer: 1 },
        { question: "Bones in an adult human body?", options: ["206", "300", "150"], answer: 0 },
        { question: "Organ that pumps blood through body?", options: ["Brain", "Heart", "Lungs"], answer: 1 },
        { question: "Speed of light (approx)?", options: ["300,000 km/s", "150,000 km/s", "1,000 km/s"], answer: 0 },
        { question: "Gas humans need to survive?", options: ["Carbon Dioxide", "Oxygen", "Helium"], answer: 1 },
        { question: "Center of an atom is called?", options: ["Nucleus", "Electron", "Proton"], answer: 0 },
        { question: "State of water vapor?", options: ["Solid", "Liquid", "Gas"], answer: 2 },
        { question: "Closest star to Earth?", options: ["Alpha Centauri", "The Sun", "Sirius"], answer: 1 },
        { question: "DNA stands for?", options: ["Deoxyribonucleic Acid", "Dual Nitrogen Acid", "Dynamic Nuclear Acid"], answer: 0 },
        { question: "Which blood type is universal donor?", options: ["A+", "O-", "AB+"], answer: 1 },
        { question: "Number of planets in solar system?", options: ["7", "8", "9"], answer: 1 },
        { question: "Which element is most abundant in atmosphere?", options: ["Oxygen", "Nitrogen", "Carbon"], answer: 1 },
        { question: "Largest organ in the human body?", options: ["Liver", "Skin", "Heart"], answer: 1 },
        { question: "Chemical formula for common salt?", options: ["NaCl", "KCl", "CaCl2"], answer: 0 },
        { question: "Sound cannot travel through?", options: ["Air", "Water", "Vacuum"], answer: 2 },
        { question: "Unit of electric current?", options: ["Volt", "Ampere", "Watt"], answer: 1 },
        { question: "What is the powerhouse of the cell?", options: ["Nucleus", "Ribosome", "Mitochondria"], answer: 2 },
        { question: "Layer that protects Earth from UV rays?", options: ["Troposphere", "Ozone Layer", "Ionosphere"], answer: 1 },
        { question: "Boiling point of water at sea level?", options: ["90°C", "100°C", "110°C"], answer: 1 },
        { question: "Which planet has rings?", options: ["Jupiter", "Saturn", "Uranus"], answer: 1 },
        { question: "Blood is filtered by which organ?", options: ["Lungs", "Stomach", "Kidneys"], answer: 2 },
        { question: "What is the atomic number of carbon?", options: ["6", "8", "12"], answer: 0 },
        { question: "Energy from the sun reaches Earth as?", options: ["Sound waves", "Light/Radiation", "Wind"], answer: 1 },
        { question: "How many chambers does the human heart have?", options: ["2", "4", "6"], answer: 1 },
        { question: "Liquid metal at room temperature?", options: ["Lead", "Mercury", "Gallium"], answer: 1 },
        { question: "Newton's 2nd Law: Force = ?", options: ["mass + velocity", "mass × acceleration", "weight ÷ mass"], answer: 1 }
    ],
    history: [
        { question: "First President of the USA?", options: ["Lincoln", "Washington", "Jefferson"], answer: 1 },
        { question: "In what year did WWII end?", options: ["1940", "1945", "1950"], answer: 1 },
        { question: "Who built the Pyramids?", options: ["Romans", "Greeks", "Egyptians"], answer: 2 },
        { question: "Empire ruled by Julius Caesar?", options: ["Roman", "Ottoman", "Mayan"], answer: 0 },
        { question: "Year Apollo 11 landed on the moon?", options: ["1969", "1975", "1959"], answer: 0 },
        { question: "Who painted the Mona Lisa?", options: ["Van Gogh", "Leonardo da Vinci", "Picasso"], answer: 1 },
        { question: "Wall dividing Berlin until 1989?", options: ["Berlin Wall", "Great Wall", "Iron Curtain"], answer: 0 },
        { question: "Famous ship that sank in 1912?", options: ["Titanic", "Britannic", "Mayflower"], answer: 0 },
        { question: "Author of US Declaration of Independence?", options: ["Washington", "Thomas Jefferson", "Franklin"], answer: 1 },
        { question: "Ancient civilization that developed democracy?", options: ["Greeks (Athens)", "Vikings", "Aztecs"], answer: 0 },
        { question: "In what year did World War I begin?", options: ["1910", "1914", "1918"], answer: 1 },
        { question: "Who was the first man to walk on the moon?", options: ["Buzz Aldrin", "Neil Armstrong", "Yuri Gagarin"], answer: 1 },
        { question: "Empire that built the Great Wall of China?", options: ["Ming Dynasty", "Roman Empire", "Han Dynasty"], answer: 0 },
        { question: "Country that was first to grant women the right to vote?", options: ["USA", "New Zealand", "UK"], answer: 1 },
        { question: "Inventor of the telephone?", options: ["Edison", "Bell", "Tesla"], answer: 1 },
        { question: "Year Christopher Columbus reached the Americas?", options: ["1492", "1500", "1482"], answer: 0 },
        { question: "Ancient wonder located in Egypt?", options: ["Colosseum", "Great Pyramid of Giza", "Machu Picchu"], answer: 1 },
        { question: "French Revolution began in which year?", options: ["1789", "1776", "1800"], answer: 0 },
        { question: "Longest-reigning British monarch?", options: ["Victoria", "Elizabeth II", "George III"], answer: 1 },
        { question: "Leader of the Cuban Revolution?", options: ["Che Guevara", "Fidel Castro", "Batista"], answer: 1 },
        { question: "Atomic bomb was first dropped on which city?", options: ["Nagasaki", "Tokyo", "Hiroshima"], answer: 2 },
        { question: "Who was Napoleon Bonaparte?", options: ["British King", "French Emperor", "Russian Tsar"], answer: 1 },
        { question: "Country that sold Louisiana to the USA?", options: ["Spain", "France", "England"], answer: 1 },
        { question: "Year the Berlin Wall fell?", options: ["1987", "1989", "1991"], answer: 1 },
        { question: "Maya civilization was primarily in which region?", options: ["South America", "Mesoamerica", "North Africa"], answer: 1 },
        { question: "Which empire was ruled by Genghis Khan?", options: ["Mongol Empire", "Ottoman Empire", "Persian Empire"], answer: 0 },
        { question: "Year India gained independence from Britain?", options: ["1945", "1947", "1950"], answer: 1 },
        { question: "Martin Luther King Jr. gave 'I Have a Dream' speech in?", options: ["1960", "1963", "1968"], answer: 1 },
        { question: "Who discovered America before Columbus?", options: ["Eric the Red", "Leif Erikson", "John Cabot"], answer: 1 },
        { question: "First Emperor of unified China?", options: ["Kublai Khan", "Qin Shi Huang", "Sun Yat-sen"], answer: 1 }
    ],
    technology: [
        { question: "What does CPU stand for?", options: ["Central Process Unit", "Central Processing Unit", "Computer Personal Unit"], answer: 1 },
        { question: "Who co-founded Microsoft?", options: ["Steve Jobs", "Bill Gates", "Elon Musk"], answer: 1 },
        { question: "Main function of RAM?", options: ["Long-term storage", "Short-term memory", "Cooling"], answer: 1 },
        { question: "What does HTML stand for?", options: ["HyperText Markup Language", "HighTech Machine Language", "Home Tool Markup Language"], answer: 0 },
        { question: "Company that created the iPhone?", options: ["Google", "Apple", "Samsung"], answer: 1 },
        { question: "What does WWW stand for?", options: ["World Wide Web", "Web World Wide", "Western World Web"], answer: 0 },
        { question: "Language used for web page styling?", options: ["Python", "CSS", "SQL"], answer: 1 },
        { question: "Brain of a computer?", options: ["CPU", "GPU", "Hard Drive"], answer: 0 },
        { question: "Binary consists of which digits?", options: ["0 and 1", "1 and 2", "0 and 9"], answer: 0 },
        { question: "SSD stands for?", options: ["Solid State Drive", "Super Storage Disk", "System Security Drive"], answer: 0 },
        { question: "Programming language created by Sun Microsystems?", options: ["Python", "Java", "C++"], answer: 1 },
        { question: "What is the function of a GPU?", options: ["Store data", "Process graphics", "Connect to internet"], answer: 1 },
        { question: "What does USB stand for?", options: ["Universal Serial Bus", "Unified System Base", "User Storage Block"], answer: 0 },
        { question: "First programmable computer was built in?", options: ["1930s", "1940s", "1950s"], answer: 1 },
        { question: "Operating system made by Apple for Mac?", options: ["Windows", "macOS", "Linux"], answer: 1 },
        { question: "What does URL stand for?", options: ["Uniform Resource Locator", "Universal Remote Link", "Unified Resource Layer"], answer: 0 },
        { question: "Who founded Facebook?", options: ["Jack Dorsey", "Mark Zuckerberg", "Larry Page"], answer: 1 },
        { question: "What does AI stand for in technology?", options: ["Automated Interaction", "Artificial Intelligence", "Advanced Internet"], answer: 1 },
        { question: "Language mainly used for data science?", options: ["Java", "Python", "Ruby"], answer: 1 },
        { question: "What does IoT stand for?", options: ["Internet of Things", "Interface of Technology", "Integrated Online Tech"], answer: 0 },
        { question: "First video game console by Nintendo?", options: ["NES", "Famicom", "Game Boy"], answer: 1 },
        { question: "What does VPN stand for?", options: ["Virtual Private Network", "Verified Public Node", "Video Proxy Network"], answer: 0 },
        { question: "PHP is a language used for?", options: ["Mobile apps", "Server-side web", "Game design"], answer: 1 },
        { question: "What does OS stand for?", options: ["Online System", "Operating System", "Open Server"], answer: 1 },
        { question: "Who invented the World Wide Web?", options: ["Bill Gates", "Tim Berners-Lee", "Vint Cerf"], answer: 1 },
        { question: "Most popular search engine in the world?", options: ["Bing", "Google", "Yahoo"], answer: 1 },
        { question: "What is open-source software?", options: ["Paid software", "Freely modifiable code", "Government software"], answer: 1 },
        { question: "Which company makes the Android OS?", options: ["Apple", "Google", "Microsoft"], answer: 1 },
        { question: "What does API stand for?", options: ["Application Programming Interface", "Automated Processing Input", "Advanced Protocol Integration"], answer: 0 },
        { question: "What is 'phishing' in cybersecurity?", options: ["A virus type", "Fake identity fraud", "Hacking a server"], answer: 1 }
    ]
};
